name: Activity proposal
description: Propose a new activity for the camp
title: "[Activity]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose some activities!
  - type: dropdown
    id: type
    attributes:
      label: Type of activity
      description: What kind of activity is this?
      options:
        - code sprint
        - tutorial
        - discussion
        - else
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is this about?
      description: Don't forget to add links/refs, to mention other participants, etc.
    validations:
      required: true
  - type: dropdown
    id: length
    attributes:
      label: How long?
      description: What amount of time do you think will be needed approximately? This will help with scheduling.
      multiple: true
      options:
        - a couple hours
        - a half-day
        - a day
        - a few days
